@echo off
for %%a in (
	"cordova-plugin-console"
	"cordova-plugin-device"
	"cordova-plugin-splashscreen"
	"cordova-plugin-statusbar"
	"cordova-plugin-whitelist"
	"ionic-plugin-keyboard"
	"cordova-plugin-file"
	"cordova-plugin-camera"
	"cordova-plugin-file-opener2"
	"cordova-plugin-file-transfer"
	"cordova-plugin-geolocation"
	"cordova-sqlite-storage"
	"cordova.plugins.diagnostic"
	"cordova-plugin-bluetooth-serial"
	"uk.co.workingedge.phonegap.plugin.launchnavigator"
	"https://github.com/wymsee/cordova-imagePicker.git"
	"https://github.com/apache/cordova-plugin-network-information"
	"https://github.com/wildabeast/BarcodeScanner.git"
	"https://github.com/phonegap/phonegap-plugin-push.git"
	"cordova-plugin-actionsheet"
	"cordova-plugin-compat"
	"cordova-plugin-contacts"
	"cordova-plugin-dialogs"
	"cordova-plugin-email-composer"
	"cordova-plugin-fcm"
	"cordova-plugin-inappbrowser"
	"cordova-plugin-keychain-touch-id"
	"cordova-plugin-x-socialsharing"
	"ionic-plugin-keyboard"
	"phonegap-nfc"
	"cordova-plugin-gpslocation"
	"cordova-plugin-request-location-accuracy"
	"cordova-plugin-screen-orientation"
	"cordova-plugin-datepicker"
) do cordova plugin add %%a